### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by haldiggs** [phunkei/autoStorage#2]
yeah I know this error sucks. It happens as soon as I call

```
$('form').autoStorage({
    'submit': true,
    'storageType': 'session'
});
```

I'm not sure what its looking for 
`var storage = jQuery.parseJSON(data.getItem("autoStorage"));`

the value is NULL for the storage variable. Obviously I'm missing something from the example. There aren't much in the way of instructions.

**Comment by phunkei** [comment]
Hi,
could you please provide the full example and browser?
